import { formatLongDate, formatMinutes, formatShortDate, formatToken } from "./formatters";

function sanitizePdfText(value) {
  return String(value ?? "")
    .replace(/[^\x20-\x7E]/g, " ")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function createText(text, x, y, font, size, color = "1 1 1") {
  return [
    "BT",
    `/${font} ${size} Tf`,
    `${color} rg`,
    `1 0 0 1 ${x} ${y} Tm`,
    `(${sanitizePdfText(text)}) Tj`,
    "ET",
  ].join("\n");
}

function drawFilledRect(x, y, width, height, color) {
  return `${color} rg\n${x} ${y} ${width} ${height} re f`;
}

function drawStrokeRect(x, y, width, height, color, lineWidth = 1) {
  return `${lineWidth} w\n${color} RG\n${x} ${y} ${width} ${height} re S`;
}

function drawLine(x1, y1, x2, y2, color, lineWidth = 1) {
  return `${lineWidth} w\n${color} RG\n${x1} ${y1} m\n${x2} ${y2} l S`;
}

function buildPdf(content) {
  const objects = [
    null,
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
  ];
  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  for (let index = 1; index < objects.length; index += 1) {
    offsets[index] = pdf.length;
    pdf += `${index} 0 obj\n${objects[index]}\nendobj\n`;
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length}\n`;
  pdf += "0000000000 65535 f \n";

  for (let index = 1; index < objects.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return new Blob([pdf], { type: "application/pdf" });
}

export function downloadInvoicePdf({
  appName = "NoWait",
  userName,
  tokenNumber,
  bookingDate,
  bookingLabel,
  estimatedTime,
  queuePosition,
  status,
}) {
  const issueDate = new Date();
  const title = `${appName} Queue Invoice`;
  const bookingDateLabel = formatLongDate(bookingDate);
  const queueText =
    typeof queuePosition === "number" && queuePosition > 0
      ? `#${queuePosition}`
      : "Active";
  const etaText =
    typeof estimatedTime === "number" && estimatedTime > 0
      ? formatMinutes(estimatedTime)
      : "Now";
  const invoiceNumber = `NW-${formatShortDate(issueDate).replace(/\s+/g, "").toUpperCase()}-${formatToken(tokenNumber)}`;
  const content = [
    drawFilledRect(0, 0, 595, 842, "0.02 0.04 0.09"),
    drawFilledRect(44, 574, 507, 212, "0.05 0.08 0.16"),
    drawStrokeRect(44, 574, 507, 212, "0.26 0.44 0.92", 1.3),
    drawFilledRect(44, 696, 507, 90, "0.10 0.16 0.32"),
    createText(appName, 68, 745, "F1", 14, "0.58 0.86 1"),
    createText(title, 68, 716, "F1", 28),
    createText("Smart Queue and Booking System", 68, 694, "F2", 11, "0.75 0.82 0.94"),
    createText(`Invoice ${invoiceNumber}`, 404, 744, "F2", 11, "0.75 0.82 0.94"),
    createText(`Issued ${formatLongDate(issueDate)}`, 369, 722, "F2", 11, "0.75 0.82 0.94"),
    drawLine(68, 670, 527, 670, "0.20 0.30 0.55"),
    createText("Passenger", 68, 642, "F2", 10, "0.56 0.64 0.84"),
    createText(userName || "NoWait User", 68, 620, "F1", 18),
    createText("Booking Day", 248, 642, "F2", 10, "0.56 0.64 0.84"),
    createText(`${bookingLabel || "Booked"} - ${bookingDateLabel}`, 248, 620, "F1", 18),
    createText("Status", 68, 585, "F2", 10, "0.56 0.64 0.84"),
    createText(String(status || "waiting").toUpperCase(), 68, 563, "F1", 16, "0.54 0.86 0.78"),
    createText("Queue Position", 248, 585, "F2", 10, "0.56 0.64 0.84"),
    createText(queueText, 248, 563, "F1", 16),
    drawFilledRect(44, 314, 507, 228, "0.03 0.06 0.12"),
    drawStrokeRect(44, 314, 507, 228, "0.16 0.22 0.40", 1),
    createText("Booking Snapshot", 68, 512, "F1", 18),
    createText("Token Number", 68, 474, "F2", 10, "0.56 0.64 0.84"),
    createText(formatToken(tokenNumber), 68, 448, "F1", 30),
    createText("Estimated Time", 248, 474, "F2", 10, "0.56 0.64 0.84"),
    createText(etaText, 248, 448, "F1", 30),
    createText("Booking Date", 68, 406, "F2", 10, "0.56 0.64 0.84"),
    createText(bookingDateLabel, 68, 382, "F1", 16),
    createText("Queue Position", 248, 406, "F2", 10, "0.56 0.64 0.84"),
    createText(queueText, 248, 382, "F1", 16),
    createText(
      "Auto-generated by NoWait. Your queue ETA updates live in the dashboard.",
      68,
      338,
      "F2",
      11,
      "0.70 0.76 0.90",
    ),
    createText("Keep this invoice for desk verification if needed.", 68, 318, "F2", 11, "0.70 0.76 0.90"),
    createText("Skip the Line. Save Your Time.", 68, 112, "F1", 16, "0.58 0.86 1"),
    createText("www.nowait.local", 68, 90, "F2", 10, "0.52 0.60 0.80"),
  ].join("\n");
  const blob = buildPdf(content);
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");

  anchor.href = url;
  anchor.download = `nowait-invoice-${bookingLabel || "booked"}-${formatToken(tokenNumber)}.pdf`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1200);
}
